// Challenge templates for random fill in AdminPanel
export const challengeTemplates = [
  {
    name: 'Block Explorer',
    description: 'Analyze a block and extract the miner address.',
    category: 'Blockchain',
    flagText: 'block{miner_address}',
    reward: '5',
    difficulty: '2',
    submissionFee: '2',
  },
  {
    name: 'Hash Hunter',
    description: 'Find the hash of a given transaction.',
    category: 'Crypto',
    flagText: 'flag{tx_hash}',
    reward: '7',
    difficulty: '3',
    submissionFee: '3',
  },
  {
    name: 'Web3 Login',
    description: 'Authenticate using your wallet.',
    category: 'Web',
    flagText: 'web3{login_success}',
    reward: '4',
    difficulty: '1',
    submissionFee: '1',
  },
  {
    name: 'Gas Saver',
    description: 'Optimize a contract for lower gas usage.',
    category: 'Blockchain',
    flagText: 'flag{gas_optimized}',
    reward: '8',
    difficulty: '4',
    submissionFee: '4',
  },
  {
    name: 'Signature Check',
    description: 'Verify a digital signature.',
    category: 'Crypto',
    flagText: 'sig{verified}',
    reward: '6',
    difficulty: '2',
    submissionFee: '2',
  },
  {
    name: 'NFT Detective',
    description: 'Find the owner of a specific NFT.',
    category: 'Blockchain',
    flagText: 'nft{owner}',
    reward: '7',
    difficulty: '3',
    submissionFee: '2',
  },
  {
    name: 'Smart Contract Audit',
    description: 'Identify a vulnerability in a contract.',
    category: 'Blockchain',
    flagText: 'audit{vuln_found}',
    reward: '10',
    difficulty: '5',
    submissionFee: '5',
  },
  {
    name: 'Token Tracker',
    description: 'Track the transfer of a token.',
    category: 'Crypto',
    flagText: 'token{transfer}',
    reward: '3',
    difficulty: '1',
    submissionFee: '1',
  },
  {
    name: 'Oracle Quest',
    description: 'Use an oracle to fetch off-chain data.',
    category: 'Web',
    flagText: 'oracle{data_fetched}',
    reward: '9',
    difficulty: '4',
    submissionFee: '4',
  },
  {
    name: 'Wallet Watcher',
    description: 'Monitor wallet activity for suspicious transactions.',
    category: 'Blockchain',
    flagText: 'wallet{activity}',
    reward: '6',
    difficulty: '2',
    submissionFee: '2',
  },
  {
    name: 'Gas Oracle',
    description: 'Predict the next block gas price accurately.',
    category: 'Blockchain',
    flagText: 'gas{oracle_predicted}',
    reward: '7',
    difficulty: '3',
    submissionFee: '2',
  },
  {
    name: 'ENS Detective',
    description: 'Find the ENS name for a given address.',
    category: 'Web',
    flagText: 'ens{resolved}',
    reward: '2',
    difficulty: '2',
    submissionFee: '1',
  },
  {
    name: 'Flash Loan Attack',
    description: 'Simulate a flash loan attack on a vulnerable contract.',
    category: 'Blockchain',
    flagText: 'flash{loaned}',
    reward: '10',
    difficulty: '5',
    submissionFee: '6',
  },
  {
    name: 'Merkle Proof',
    description: 'Provide a valid Merkle proof for a leaf node.',
    category: 'Crypto',
    flagText: 'merkle{proof_valid}',
    reward: '6',
    difficulty: '3',
    submissionFee: '2',
  },
  {
    name: 'Timestamp Trick',
    description: 'Exploit a contract using block.timestamp.',
    category: 'Blockchain',
    flagText: 'timestamp{exploited}',
    reward: '9',
    difficulty: '4',
    submissionFee: '3',
  },
  {
    name: 'Phishing Filter',
    description: 'Detect a phishing website from a list.',
    category: 'Web',
    flagText: 'phish{caught}',
    reward: '2',
    difficulty: '2',
    submissionFee: '1',
  },
  {
    name: 'Reentrancy Guard',
    description: 'Patch a contract to prevent reentrancy.',
    category: 'Blockchain',
    flagText: 'reentrancy{guarded}',
    reward: '8',
    difficulty: '4',
    submissionFee: '3',
  },
  {
    name: 'Zero-Knowledge Proof',
    description: 'Submit a valid zk-SNARK proof.',
    category: 'Crypto',
    flagText: 'zk{snark_passed}',
    reward: '10',
    difficulty: '5',
    submissionFee: '7',
  },
  {
    name: 'Gasless MetaTx',
    description: 'Relay a transaction using meta-transactions.',
    category: 'Web',
    flagText: 'meta{tx_relayed}',
    reward: '5',
    difficulty: '3',
    submissionFee: '1',
  },
  {
    name: 'DEX Arbitrage',
    description: 'Find an arbitrage opportunity between two DEXs.',
    category: 'Blockchain',
    flagText: 'arbitrage{profit}',
    reward: '9',
    difficulty: '4',
    submissionFee: '4',
  },
  {
    name: 'MultiSig Master',
    description: 'Execute a transaction with a multisig wallet.',
    category: 'Crypto',
    flagText: 'multisig{executed}',
    reward: '8',
    difficulty: '3',
    submissionFee: '2',
  },
]; 